/** Kinesiology curriculum layered on the Rajagopal coordinates.
 * Slider limits for model joints come from the published coordinate ranges.
 * Clinical numbers are the adult guides commonly taken from AAOS and from
 * Norkin & White, Measurement of Joint Motion. They are population guides.
 */

export const MUSCLES = {
  iliacus: { title: "Iliacus", origin: "Iliac fossa", insertion: "Lesser trochanter", nerve: "Femoral nerve", actions: "Hip flexion. Anterior pelvic tilt when the femur is fixed." },
  psoas: { title: "Psoas major", origin: "T12–L5 vertebral bodies and discs", insertion: "Lesser trochanter", nerve: "Ventral rami L1–L3", actions: "Hip flexion. Can increase lumbar lordosis." },
  recfem: { title: "Rectus femoris", origin: "AIIS and the rim of the acetabulum", insertion: "Tibial tuberosity via the patellar tendon", nerve: "Femoral nerve", actions: "Hip flexion and knee extension." },
  sart: { title: "Sartorius", origin: "ASIS", insertion: "Pes anserinus on the medial tibia", nerve: "Femoral nerve", actions: "Hip flexion, abduction, and external rotation. Knee flexion." },
  tfl: { title: "Tensor fasciae latae", origin: "Iliac crest and ASIS", insertion: "Iliotibial tract, lateral tibia", nerve: "Superior gluteal nerve", actions: "Hip flexion, abduction, and internal rotation. Steadies the knee through the IT band." },
  addlong: { title: "Adductor longus", origin: "Body of the pubis", insertion: "Middle third of the linea aspera", nerve: "Obturator nerve", actions: "Hip adduction. Assists hip flexion." },
  addbrev: { title: "Adductor brevis", origin: "Inferior pubic ramus", insertion: "Proximal linea aspera", nerve: "Obturator nerve", actions: "Hip adduction. Assists flexion." },
  addmagProx: { title: "Adductor magnus, proximal", origin: "Inferior pubic ramus", insertion: "Proximal linea aspera", nerve: "Obturator nerve", actions: "Hip adduction." },
  addmagMid: { title: "Adductor magnus, middle", origin: "Ischiopubic ramus", insertion: "Middle linea aspera", nerve: "Obturator nerve", actions: "Hip adduction." },
  addmagDist: { title: "Adductor magnus, distal", origin: "Ischiopubic ramus", insertion: "Distal linea aspera and medial supracondylar line", nerve: "Obturator nerve", actions: "Hip adduction." },
  addmagIsch: { title: "Adductor magnus, ischial part", origin: "Ischial tuberosity", insertion: "Adductor tubercle", nerve: "Tibial part of the sciatic nerve", actions: "Hip adduction and extension." },
  grac: { title: "Gracilis", origin: "Inferior pubic ramus", insertion: "Pes anserinus", nerve: "Obturator nerve", actions: "Hip adduction. Assists knee flexion." },
  glmax1: { title: "Gluteus maximus, upper", origin: "Ilium, sacrum, sacrotuberous ligament", insertion: "Iliotibial tract", nerve: "Inferior gluteal nerve", actions: "Hip extension and external rotation. Upper fibers also abduct." },
  glmax2: { title: "Gluteus maximus, middle", origin: "Ilium and sacrum", insertion: "Iliotibial tract and gluteal tuberosity", nerve: "Inferior gluteal nerve", actions: "Hip extension and external rotation." },
  glmax3: { title: "Gluteus maximus, lower", origin: "Sacrum and coccyx", insertion: "Gluteal tuberosity", nerve: "Inferior gluteal nerve", actions: "Hip extension and external rotation. Lower fibers also adduct." },
  glmed1: { title: "Gluteus medius, anterior", origin: "Ilium between the gluteal lines", insertion: "Greater trochanter", nerve: "Superior gluteal nerve", actions: "Hip abduction and internal rotation." },
  glmed2: { title: "Gluteus medius, middle", origin: "Ilium", insertion: "Greater trochanter", nerve: "Superior gluteal nerve", actions: "Hip abduction. Holds the pelvis level in single-leg stance." },
  glmed3: { title: "Gluteus medius, posterior", origin: "Ilium", insertion: "Greater trochanter", nerve: "Superior gluteal nerve", actions: "Hip abduction and external rotation." },
  glmin1: { title: "Gluteus minimus, anterior", origin: "Ilium", insertion: "Greater trochanter", nerve: "Superior gluteal nerve", actions: "Hip abduction and internal rotation." },
  glmin2: { title: "Gluteus minimus, middle", origin: "Ilium", insertion: "Greater trochanter", nerve: "Superior gluteal nerve", actions: "Hip abduction." },
  glmin3: { title: "Gluteus minimus, posterior", origin: "Ilium", insertion: "Greater trochanter", nerve: "Superior gluteal nerve", actions: "Hip abduction and external rotation." },
  piri: { title: "Piriformis", origin: "Anterior sacrum", insertion: "Greater trochanter", nerve: "Nerve to piriformis", actions: "Hip external rotation. Abducts once the hip is flexed." },
  bflh: { title: "Biceps femoris, long head", origin: "Ischial tuberosity", insertion: "Fibular head", nerve: "Tibial part of the sciatic nerve", actions: "Hip extension and knee flexion. Laterally rotates a flexed knee." },
  bfsh: { title: "Biceps femoris, short head", origin: "Linea aspera", insertion: "Fibular head", nerve: "Common fibular part of the sciatic nerve", actions: "Knee flexion only. The short head does not cross the hip." },
  semimem: { title: "Semimembranosus", origin: "Ischial tuberosity", insertion: "Posterior medial tibial condyle", nerve: "Tibial part of the sciatic nerve", actions: "Hip extension and knee flexion. Medially rotates a flexed knee." },
  semiten: { title: "Semitendinosus", origin: "Ischial tuberosity", insertion: "Pes anserinus", nerve: "Tibial part of the sciatic nerve", actions: "Hip extension and knee flexion." },
  vaslat: { title: "Vastus lateralis", origin: "Lateral femur and linea aspera", insertion: "Patella and tibial tuberosity", nerve: "Femoral nerve", actions: "Knee extension." },
  vasmed: { title: "Vastus medialis", origin: "Medial femur and linea aspera", insertion: "Patella and tibial tuberosity", nerve: "Femoral nerve", actions: "Knee extension. Distal fibers help keep the patella tracking." },
  vasint: { title: "Vastus intermedius", origin: "Anterior femur", insertion: "Patella and tibial tuberosity", nerve: "Femoral nerve", actions: "Knee extension." },
  gaslat: { title: "Gastrocnemius, lateral", origin: "Lateral femoral condyle", insertion: "Calcaneus via the Achilles tendon", nerve: "Tibial nerve", actions: "Ankle plantarflexion and knee flexion." },
  gasmed: { title: "Gastrocnemius, medial", origin: "Medial femoral condyle", insertion: "Calcaneus via the Achilles tendon", nerve: "Tibial nerve", actions: "Ankle plantarflexion and knee flexion." },
  soleus: { title: "Soleus", origin: "Posterior tibia and fibula, soleal line", insertion: "Calcaneus via the Achilles tendon", nerve: "Tibial nerve", actions: "Ankle plantarflexion. Does not cross the knee." },
  tibant: { title: "Tibialis anterior", origin: "Lateral tibia and interosseous membrane", insertion: "Medial cuneiform and first metatarsal", nerve: "Deep fibular nerve", actions: "Dorsiflexion and inversion." },
  tibpost: { title: "Tibialis posterior", origin: "Posterior tibia and fibula", insertion: "Navicular, cuneiforms, and metatarsal bases", nerve: "Tibial nerve", actions: "Inversion and plantarflexion. Supports the medial arch." },
  edl: { title: "Extensor digitorum longus", origin: "Lateral tibial condyle and fibula", insertion: "Dorsal expansions of toes 2–5", nerve: "Deep fibular nerve", actions: "Toe extension and dorsiflexion." },
  ehl: { title: "Extensor hallucis longus", origin: "Fibula and interosseous membrane", insertion: "Distal phalanx of the great toe", nerve: "Deep fibular nerve", actions: "Great-toe extension and dorsiflexion." },
  fdl: { title: "Flexor digitorum longus", origin: "Posterior tibia", insertion: "Distal phalanges of toes 2–5", nerve: "Tibial nerve", actions: "Toe flexion and plantarflexion." },
  fhl: { title: "Flexor hallucis longus", origin: "Posterior fibula", insertion: "Distal phalanx of the great toe", nerve: "Tibial nerve", actions: "Great-toe flexion and plantarflexion." },
  perlong: { title: "Fibularis longus", origin: "Proximal fibula", insertion: "Medial cuneiform and first metatarsal", nerve: "Superficial fibular nerve", actions: "Eversion and plantarflexion." },
  perbrev: { title: "Fibularis brevis", origin: "Distal fibula", insertion: "Base of the fifth metatarsal", nerve: "Superficial fibular nerve", actions: "Eversion and plantarflexion." },
  deltoid_ant: { title: "Anterior deltoid", origin: "Lateral third of the clavicle", insertion: "Deltoid tuberosity", nerve: "Axillary nerve", actions: "Shoulder flexion and internal rotation." },
  deltoid_mid: { title: "Middle deltoid", origin: "Acromion", insertion: "Deltoid tuberosity", nerve: "Axillary nerve", actions: "Shoulder abduction, after supraspinatus starts the motion." },
  deltoid_post: { title: "Posterior deltoid", origin: "Spine of the scapula", insertion: "Deltoid tuberosity", nerve: "Axillary nerve", actions: "Shoulder extension and external rotation." },
  supraspinatus: { title: "Supraspinatus", origin: "Supraspinous fossa", insertion: "Greater tubercle", nerve: "Suprascapular nerve", actions: "Starts abduction and compresses the humeral head into the glenoid." },
  infraspinatus: { title: "Infraspinatus", origin: "Infraspinous fossa", insertion: "Greater tubercle", nerve: "Suprascapular nerve", actions: "External rotation. Resists upward shear of the humeral head." },
  subscapularis: { title: "Subscapularis", origin: "Subscapular fossa", insertion: "Lesser tubercle", nerve: "Upper and lower subscapular nerves", actions: "Internal rotation." },
  teres_minor: { title: "Teres minor", origin: "Lateral border of the scapula", insertion: "Greater tubercle", nerve: "Axillary nerve", actions: "External rotation." },
  teres_major: { title: "Teres major", origin: "Inferior angle of the scapula", insertion: "Medial lip of the intertubercular groove", nerve: "Lower subscapular nerve", actions: "Extension, adduction, and internal rotation." },
  pec_major: { title: "Pectoralis major", origin: "Clavicle, sternum, and costal cartilages", insertion: "Lateral lip of the intertubercular groove", nerve: "Lateral and medial pectoral nerves", actions: "Adduction, internal rotation, and horizontal adduction. The clavicular head flexes." },
  latissimus: { title: "Latissimus dorsi", origin: "Spinous processes, thoracolumbar fascia, iliac crest", insertion: "Floor of the intertubercular groove", nerve: "Thoracodorsal nerve", actions: "Extension, adduction, and internal rotation." },
  coracobrachialis: { title: "Coracobrachialis", origin: "Coracoid process", insertion: "Medial humerus", nerve: "Musculocutaneous nerve", actions: "Shoulder flexion and adduction." },
  biceps: { title: "Biceps brachii", origin: "Supraglenoid tubercle and coracoid process", insertion: "Radial tuberosity and bicipital aponeurosis", nerve: "Musculocutaneous nerve", actions: "Elbow flexion, forearm supination, and a weak shoulder flexion." },
  brachialis: { title: "Brachialis", origin: "Anterior humerus", insertion: "Ulnar tuberosity and coronoid process", nerve: "Musculocutaneous nerve", actions: "Elbow flexion in every forearm position." },
  triceps_long: { title: "Triceps, long head", origin: "Infraglenoid tubercle", insertion: "Olecranon", nerve: "Radial nerve", actions: "Elbow extension and shoulder extension." },
  triceps_lat: { title: "Triceps, lateral head", origin: "Posterior humerus above the radial groove", insertion: "Olecranon", nerve: "Radial nerve", actions: "Elbow extension." },
  brachioradialis: { title: "Brachioradialis", origin: "Lateral supracondylar ridge", insertion: "Radial styloid", nerve: "Radial nerve", actions: "Elbow flexion, strongest in mid-pronation." },
  pronator_teres: { title: "Pronator teres", origin: "Medial epicondyle and coronoid", insertion: "Lateral radius", nerve: "Median nerve", actions: "Pronation and weak elbow flexion." },
  supinator: { title: "Supinator", origin: "Lateral epicondyle and proximal ulna", insertion: "Proximal radius", nerve: "Radial nerve, deep branch", actions: "Supination, including with the elbow extended." },
  fcr: { title: "Flexor carpi radialis", origin: "Medial epicondyle", insertion: "Bases of metacarpals 2 and 3", nerve: "Median nerve", actions: "Wrist flexion and radial deviation." },
  fcu: { title: "Flexor carpi ulnaris", origin: "Medial epicondyle and olecranon", insertion: "Pisiform, hamate, and fifth metacarpal", nerve: "Ulnar nerve", actions: "Wrist flexion and ulnar deviation." },
  ecrl: { title: "Extensor carpi radialis longus", origin: "Lateral supracondylar ridge", insertion: "Base of the second metacarpal", nerve: "Radial nerve", actions: "Wrist extension and radial deviation." },
  ecu: { title: "Extensor carpi ulnaris", origin: "Lateral epicondyle and ulna", insertion: "Base of the fifth metacarpal", nerve: "Radial nerve, deep branch", actions: "Wrist extension and ulnar deviation." },
  edc: { title: "Extensor digitorum", origin: "Lateral epicondyle", insertion: "Extensor expansions of digits 2–5", nerve: "Radial nerve, deep branch", actions: "Extends the fingers at the MCP joints and assists wrist extension." },
  fds: { title: "Flexor digitorum superficialis", origin: "Medial epicondyle, ulna, and radius", insertion: "Middle phalanges of digits 2–5", nerve: "Median nerve", actions: "Flexes the PIP joints and assists wrist flexion." },
  upper_trap: { title: "Upper trapezius", origin: "Occiput and nuchal ligament", insertion: "Lateral clavicle and acromion", nerve: "Spinal accessory nerve", actions: "Scapular elevation and upward rotation. Extends and side-bends the neck." },
  mid_trap: { title: "Middle trapezius", origin: "Upper thoracic spinous processes", insertion: "Scapular spine", nerve: "Spinal accessory nerve", actions: "Scapular retraction." },
  lower_trap: { title: "Lower trapezius", origin: "Lower thoracic spinous processes", insertion: "Root of the scapular spine", nerve: "Spinal accessory nerve", actions: "Scapular depression and upward rotation." },
  levator: { title: "Levator scapulae", origin: "Transverse processes C1–C4", insertion: "Superior angle of the scapula", nerve: "Dorsal scapular nerve and C3–C4", actions: "Scapular elevation and downward rotation." },
  rhomboid: { title: "Rhomboids", origin: "C7–T5 spinous processes", insertion: "Medial border of the scapula", nerve: "Dorsal scapular nerve", actions: "Scapular retraction and downward rotation." },
  serratus: { title: "Serratus anterior", origin: "Ribs 1–8", insertion: "Medial border of the scapula, anterior surface", nerve: "Long thoracic nerve", actions: "Protraction and upward rotation. Holds the scapula on the rib cage." },
  scm: { title: "Sternocleidomastoid", origin: "Sternum and medial clavicle", insertion: "Mastoid process", nerve: "Spinal accessory nerve", actions: "Both sides flex the neck. One side rotates the face to the opposite side and side-bends to the same side." },
  erector: { title: "Erector spinae", origin: "Sacrum, iliac crest, and spinous processes", insertion: "Ribs, transverse and spinous processes, skull", nerve: "Dorsal rami", actions: "Extends the trunk and neck. One side side-bends and rotates toward the same side." },
};

const hip = (id, positive, negative, plane, axis, about, clinical, positiveMuscles, negativeMuscles, extra = {}) => ({
  id, positive, negative, plane, axis, about, clinical, positiveMuscles, negativeMuscles, ...extra,
});

const m = (id, role) => ({ id, role });

export const JOINTS = [
  {
    id: "pelvis",
    title: "Pelvis",
    region: "Trunk",
    sided: false,
    kind: "model",
    summary: "Tilt, hike, and rotation turn the pelvis and trunk on the femoral heads. The thighs stay with the hip sliders.",
    bodies: ["pelvis"],
    dofs: [
      hip("pelvis_tilt", "Posterior tilt", "Anterior tilt", "Sagittal", "Mediolateral",
        "Posterior tilt rolls the top of the pelvis and the trunk backward over both femoral heads. Anterior tilt drops the ASIS forward. The thighs stay where the hip sliders left them, so the hip angle changes inside the joint.",
        "A useful clinical window is roughly 10–15° either side of a comfortable standing tilt.",
        [m("glmax1", "prime"), m("glmax2", "prime"), m("bflh", "synergist"), m("semimem", "synergist")],
        [m("iliacus", "prime"), m("psoas", "prime"), m("recfem", "synergist"), m("erector", "synergist")],
        { uiMin: -20, uiMax: 20 }),
      hip("pelvis_list", "Right side higher", "Left side higher", "Frontal", "Anteroposterior",
        "One iliac crest hikes and the other drops. The trunk rides with the pelvis. The thighs stay vertical under the moving hip joints instead of leaning with the whole body.",
        "A few degrees of obliquity are normal in gait. Large list means the pelvis is dropping on the unloaded side.",
        [m("glmed1", "prime"), m("glmed2", "prime"), m("glmin1", "synergist")],
        [m("glmed1", "prime"), m("glmed2", "prime"), m("glmin2", "synergist")],
        { uiMin: -15, uiMax: 15 }),
      hip("pelvis_rotation", "Rotation to the left", "Rotation to the right", "Transverse", "Vertical",
        "The pelvis and trunk turn in the transverse plane over the femoral heads. The thighs do not turn with them.",
        "Walking uses roughly 5° each way.",
        [m("glmax1", "synergist"), m("piri", "synergist")],
        [m("glmax1", "synergist"), m("piri", "synergist")],
        { uiMin: -20, uiMax: 20 }),
    ],
  },
  {
    id: "lumbar",
    title: "Trunk",
    region: "Trunk",
    sided: false,
    kind: "model",
    summary: "One lumbar joint moves the entire torso, rib cage, scapulae, and head together. Neck motion is separate, and approximate, under Neck.",
    bodies: ["torso"],
    dofs: [
      hip("lumbar_extension", "Extension", "Flexion", "Sagittal", "Mediolateral",
        "Extension increases the lumbar lordosis and carries the chest backward. Flexion flattens the lordosis and folds the trunk forward. Because the scapulae ride on this torso, they come with it.",
        "Thoracolumbar flexion is often taught near 80° and extension near 25–30°. This gait model can fold much farther, so the slider stops at a teaching range.",
        [m("erector", "prime"), m("glmax1", "synergist")],
        [m("psoas", "synergist"), m("recfem", "synergist")],
        { uiMin: -70, uiMax: 30 }),
      hip("lumbar_bending", "Right lateral flexion", "Left lateral flexion", "Frontal", "Anteroposterior",
        "Lateral flexion side-bends the trunk. The same-side erector spinae, quadratus lumborum, and obliques do the work. The obliques are not separate paths in this model.",
        "About 35° each way is a typical adult guide.",
        [m("erector", "prime")],
        [m("erector", "prime")],
        { uiMin: -35, uiMax: 35 }),
      hip("lumbar_rotation", "Rotation to the left", "Rotation to the right", "Transverse", "Vertical",
        "Axial rotation of the trunk is mostly thoracic. The lumbar facets allow only a little. Internal and external obliques are the prime movers and are named here even though the gait model has no oblique paths.",
        "About 30–45° each way for the whole trunk.",
        [m("erector", "synergist")],
        [m("erector", "synergist")],
        { uiMin: -40, uiMax: 40 }),
    ],
  },
  {
    id: "cervical",
    title: "Neck",
    region: "Trunk",
    sided: false,
    kind: "teaching",
    summary: "The published gait model welds the skull to the torso. This neck pivot is a teaching approximation at the base of the skull, using clinical ranges, not a stack of validated intervertebral joints.",
    bodies: ["torso"],
    dofs: [
      hip("cervical_flexion", "Flexion", "Extension", "Sagittal", "Mediolateral",
        "Flexion nods the chin toward the chest. Extension lifts the chin. Both sternocleidomastoids flex; the suboccipitals and erector spinae extend.",
        "About 45° of flexion and 45° of extension.",
        [m("scm", "prime")],
        [m("erector", "prime"), m("upper_trap", "synergist")],
        { uiMin: -45, uiMax: 45 }),
      hip("cervical_lateral", "Right lateral flexion", "Left lateral flexion", "Frontal", "Anteroposterior",
        "Side-bending is done by the same-side sternocleidomastoid, upper trapezius, scalenes, and erector spinae.",
        "About 45° each way.",
        [m("scm", "prime"), m("upper_trap", "synergist"), m("erector", "synergist")],
        [m("scm", "prime"), m("upper_trap", "synergist"), m("levator", "synergist")],
        { uiMin: -45, uiMax: 45 }),
      hip("cervical_rotation", "Rotation to the left", "Rotation to the right", "Transverse", "Vertical",
        "Turning the face left is driven by the right sternocleidomastoid and the left suboccipitals and splenius. One SCM rotates to the opposite side.",
        "About 60° each way.",
        [m("scm", "prime")],
        [m("scm", "prime")],
        { uiMin: -60, uiMax: 60 }),
    ],
  },
  {
    id: "scapula",
    title: "Scapula",
    region: "Upper limb",
    sided: true,
    kind: "lesson",
    summary: "The scapula and clavicle are baked into the rib-cage mesh, so they cannot slide on their own. These are the movements you still have to know. Full arm elevation is glenohumeral motion plus scapular upward rotation, about 2° at the shoulder for every 1° at the scapula.",
    bodies: ["torso"],
    movements: [
      { name: "Elevation", plane: "Frontal", about: "The scapula slides up the rib cage.", muscles: [m("upper_trap", "prime"), m("levator", "prime")] },
      { name: "Depression", plane: "Frontal", about: "The scapula slides down. Lower trapezius and latissimus contribute, and pectoralis minor, which is not drawn.", muscles: [m("lower_trap", "prime"), m("latissimus", "synergist")] },
      { name: "Protraction", plane: "Transverse", about: "The scapula slides forward around the ribs, as in a push or a reach.", muscles: [m("serratus", "prime"), m("pec_major", "synergist")] },
      { name: "Retraction", plane: "Transverse", about: "The scapula slides back toward the spine, pinching the shoulder blades.", muscles: [m("mid_trap", "prime"), m("rhomboid", "prime")] },
      { name: "Upward rotation", plane: "Frontal", about: "The glenoid tilts up. Required for abduction past about 90°. Force couple: upper trapezius, lower trapezius, serratus anterior.", muscles: [m("upper_trap", "prime"), m("lower_trap", "prime"), m("serratus", "prime")] },
      { name: "Downward rotation", plane: "Frontal", about: "The glenoid tilts down, as in a lat pulldown or a backward reach.", muscles: [m("rhomboid", "prime"), m("levator", "synergist"), m("latissimus", "synergist")] },
    ],
  },
  {
    id: "shoulder",
    title: "Shoulder",
    region: "Upper limb",
    sided: true,
    kind: "model",
    summary: "This joint is the glenohumeral joint only. The model stops flexion at 90° and abduction near 120°, which is close to what the glenoid can do before the scapula has to rotate upward. Reaching overhead to 180° needs the scapular lesson as well.",
    bodies: ["humerus"],
    dofs: [
      hip("arm_flex", "Flexion", "Extension", "Sagittal", "Mediolateral",
        "Flexion lifts the arm forward. Extension carries it backward. Past 90° of real flexion, the scapula is doing a large share of the motion.",
        "Clinical flexion is about 180° and extension about 60°. This coordinate stops at ±90°.",
        [m("deltoid_ant", "prime"), m("pec_major", "synergist"), m("coracobrachialis", "synergist"), m("biceps", "synergist")],
        [m("latissimus", "prime"), m("deltoid_post", "prime"), m("teres_major", "synergist"), m("triceps_long", "synergist")],
      ),
      hip("arm_add", "Adduction", "Abduction", "Frontal", "Anteroposterior",
        "Abduction lifts the arm out to the side. Supraspinatus starts it and seats the humeral head. The middle deltoid takes over. The slider's abduction end is the model's glenohumeral limit, not a full overhead reach.",
        "Clinical abduction is about 180°, of which roughly 120° is glenohumeral. Adduction past the thigh is about 30–40° if the arm is allowed to cross the body.",
        [m("latissimus", "prime"), m("pec_major", "prime"), m("teres_major", "synergist"), m("coracobrachialis", "synergist")],
        [m("deltoid_mid", "prime"), m("supraspinatus", "prime")],
      ),
      hip("arm_rot", "Internal rotation", "External rotation", "Transverse", "Along the humerus",
        "Internal rotation turns the front of the arm toward the midline. External rotation turns it out. Measured with the elbow flexed so the forearm shows the rotation.",
        "About 70° of internal rotation and 90° of external rotation with the arm at the side.",
        [m("subscapularis", "prime"), m("latissimus", "synergist"), m("teres_major", "synergist"), m("pec_major", "synergist"), m("deltoid_ant", "synergist")],
        [m("infraspinatus", "prime"), m("teres_minor", "prime"), m("deltoid_post", "synergist")],
        { uiMin: -90, uiMax: 70 }),
    ],
  },
  {
    id: "elbow",
    title: "Elbow",
    region: "Upper limb",
    sided: true,
    kind: "model",
    summary: "A hinge. The carrying angle is built into the bone meshes. Flexion is limited by the coronoid in the coronoid fossa and by the muscle bulk of the arm.",
    bodies: ["ulna"],
    dofs: [
      hip("elbow_flex", "Flexion", "Extension", "Sagittal", "Mediolateral",
        "Flexion brings the hand toward the shoulder. Extension straightens the elbow. Most adults do not hyperextend, so the model starts at 0°.",
        "About 150° of flexion. Extension returns to 0°.",
        [m("brachialis", "prime"), m("biceps", "prime"), m("brachioradialis", "synergist")],
        [m("triceps_long", "prime"), m("triceps_lat", "prime")],
      ),
    ],
  },
  {
    id: "forearm",
    title: "Forearm",
    region: "Upper limb",
    sided: true,
    kind: "model",
    summary: "Pronation and supination spin the radius around the ulna. The hand is attached to the radius, so it turns with it. The ulna stays put, apart from a small sway at the distal radioulnar joint that this model does not separate.",
    bodies: ["radius", "hand"],
    dofs: [
      hip("pro_sup", "Pronation", "Supination", "Transverse", "From radial head to ulnar head",
        "At 0° the forearm is in the model's resting pose, which is supinated: palm facing forward with the arm at the side. Pronation turns the palm to face backward. The biceps is a strong supinator only when the elbow is somewhat flexed. The supinator still works with the elbow straight.",
        "About 80° of pronation and 80° of supination from a thumbs-up midposition. This coordinate runs from the supinated rest pose through 90° of pronation.",
        [m("pronator_teres", "prime")],
        [m("biceps", "prime"), m("supinator", "prime")],
      ),
    ],
  },
  {
    id: "wrist",
    title: "Wrist",
    region: "Upper limb",
    sided: true,
    kind: "model",
    summary: "Flexion and extension are mostly radiocarpal. Deviation is shared with the midcarpal joint. The carpal bones are present but they ride along as one hand, so this is not a carpal-by-carpal model.",
    bodies: ["hand"],
    dofs: [
      hip("wrist_flex", "Flexion", "Extension", "Sagittal", "Mediolateral",
        "Flexion bends the palm toward the forearm. Extension bends the back of the hand toward the forearm. The finger flexors assist wrist flexion only if the fingers are not already gripping hard.",
        "About 80° of flexion and 70° of extension. The model allows about ±70°.",
        [m("fcr", "prime"), m("fcu", "prime"), m("fds", "synergist")],
        [m("ecrl", "prime"), m("ecu", "prime"), m("edc", "synergist")],
      ),
      hip("wrist_dev", "Ulnar deviation", "Radial deviation", "Frontal", "Anteroposterior",
        "Ulnar deviation tips the hand toward the little finger. Radial deviation tips it toward the thumb. Deviation is largest when the wrist is near neutral flexion.",
        "About 30° ulnar and 20° radial. The model allows roughly 35° and 25°.",
        [m("fcu", "prime"), m("ecu", "prime")],
        [m("fcr", "prime"), m("ecrl", "prime")],
      ),
    ],
  },
  {
    id: "fingers",
    title: "Fingers",
    region: "Upper limb",
    sided: true,
    kind: "teaching",
    summary: "The Rajagopal hand is one rigid body. These hinges are placed where the metacarpal heads meet the phalanges, so you can see a grasp. They are not measured cadaver joint centers.",
    bodies: ["hand"],
    dofs: [
      hip("finger_curl", "Flexion", "Extension", "Sagittal", "Through the metacarpal heads",
        "A combined curl. The MCP, PIP, and DIP joints flex together, with the PIP going slightly farther, which is how a fist closes. Lumbricals and interossei flex the MCP joints and extend the IP joints, so a pure intrinsic grip looks different from this long-flexor curl.",
        "MCP flexion about 90°, PIP about 100°, DIP about 90°.",
        [m("fds", "prime")],
        [m("edc", "prime")],
        { uiMin: 0, uiMax: 90 }),
      hip("thumb_flexion", "Flexion", "Extension", "Along the thumb", "Across the thumb",
        "Thumb flexion bends the thumb across the palm. Opposition, the pad-to-pad motion that makes a precision grip, also needs abduction and rotation at the carpometacarpal joint, which this single hinge cannot separate.",
        "MCP flexion of the thumb is about 50°.",
        [m("fds", "synergist")],
        [m("edc", "synergist")],
        { uiMin: 0, uiMax: 50 }),
    ],
  },
  {
    id: "hip",
    title: "Hip",
    region: "Lower limb",
    sided: true,
    kind: "model",
    summary: "A ball and socket with three degrees of freedom. Paths are the 2016 model's muscle lines, including the compartments of gluteus maximus, medius, and minimus.",
    bodies: ["femur"],
    dofs: [
      hip("hip_flexion", "Flexion", "Extension", "Sagittal", "Mediolateral",
        "Flexion brings the thigh toward the chest. Extension carries it behind the trunk. Iliopsoas is the prime flexor. The hamstrings and gluteus maximus extend. Rectus femoris flexes the hip only when the knee is not already extended hard.",
        "About 120° of flexion and 30° of extension. This model uses that same window.",
        [m("iliacus", "prime"), m("psoas", "prime"), m("recfem", "synergist"), m("sart", "synergist"), m("tfl", "synergist"), m("addlong", "synergist")],
        [m("glmax1", "prime"), m("glmax2", "prime"), m("glmax3", "prime"), m("bflh", "synergist"), m("semimem", "synergist"), m("semiten", "synergist"), m("addmagIsch", "synergist")],
      ),
      hip("hip_adduction", "Adduction", "Abduction", "Frontal", "Anteroposterior",
        "Adduction brings the thigh toward the midline. Abduction carries it away. In single-leg stance the abductors of the stance hip stop the pelvis dropping, which is the same torque as abduction.",
        "About 45° of abduction and 20–30° of adduction. The model allows about 50° and 30°.",
        [m("addlong", "prime"), m("addbrev", "prime"), m("addmagProx", "prime"), m("addmagMid", "synergist"), m("addmagDist", "synergist"), m("addmagIsch", "synergist"), m("grac", "synergist")],
        [m("glmed1", "prime"), m("glmed2", "prime"), m("glmed3", "prime"), m("glmin1", "synergist"), m("glmin2", "synergist"), m("tfl", "synergist")],
      ),
      hip("hip_rotation", "Internal rotation", "External rotation", "Transverse", "Along the femur",
        "Internal rotation turns the kneecap inward. External rotation turns it outward. Measured with the hip flexed or with the knee flexed in sitting. Piriformis is an external rotator in anatomical position and an abductor once the hip is flexed past about 60°.",
        "About 45° each way. The model allows 40°.",
        [m("glmed1", "prime"), m("glmin1", "prime"), m("tfl", "synergist")],
        [m("glmax1", "prime"), m("glmax2", "prime"), m("glmax3", "prime"), m("piri", "prime"), m("glmed3", "synergist"), m("sart", "synergist")],
      ),
    ],
  },
  {
    id: "knee",
    title: "Knee",
    region: "Lower limb",
    sided: true,
    kind: "model",
    summary: "The tibiofemoral joint is the Walker knee from the gait model: flexion plus the small sliding and rocking that keep the joint surfaces together. The patella follows that flexion. The screw-home rotation of the last few degrees of extension is inside that coupled motion, not a separate slider.",
    bodies: ["tibia", "patella"],
    dofs: [
      hip("knee_angle", "Flexion", "Extension", "Sagittal", "Mediolateral",
        "Flexion bends the heel toward the buttock. Extension straightens the knee. The quadriceps extend. The hamstrings flex, and gastrocnemius helps when the foot is free. Vastii do not cross the hip, so they extend the knee without a hip torque.",
        "About 135° of flexion in adults. This 2016 gait model stops at 120°. A later revision of the same model (Lai 2017) was built for deeper flexion.",
        [m("bflh", "prime"), m("bfsh", "prime"), m("semimem", "prime"), m("semiten", "prime"), m("gasmed", "synergist"), m("gaslat", "synergist"), m("sart", "synergist"), m("grac", "synergist")],
        [m("recfem", "prime"), m("vaslat", "prime"), m("vasmed", "prime"), m("vasint", "prime")],
      ),
    ],
  },
  {
    id: "ankle",
    title: "Ankle",
    region: "Lower limb",
    sided: true,
    kind: "model",
    summary: "The talocrural joint. Its axis runs slightly down and back from medial to lateral, so dorsiflexion brings the foot up and a little out, and plantarflexion points it down and a little in. The model keeps that oblique axis.",
    bodies: ["talus"],
    dofs: [
      hip("ankle_angle", "Dorsiflexion", "Plantarflexion", "Sagittal", "Through the malleoli",
        "Dorsiflexion lifts the foot toward the shin. Plantarflexion points it away, as in a heel raise. Soleus is the postural plantarflexor. Gastrocnemius adds power when the knee is extended.",
        "Often taught as 20° dorsiflexion and 50° plantarflexion. This model allows about 30° and 40°.",
        [m("tibant", "prime"), m("edl", "synergist"), m("ehl", "synergist")],
        [m("soleus", "prime"), m("gasmed", "prime"), m("gaslat", "prime"), m("tibpost", "synergist"), m("perlong", "synergist"), m("perbrev", "synergist"), m("fdl", "synergist"), m("fhl", "synergist")],
      ),
    ],
  },
  {
    id: "subtalar",
    title: "Subtalar joint",
    region: "Lower limb",
    sided: true,
    kind: "model",
    summary: "Inversion and eversion happen here, between the talus and the calcaneus, not at the ankle hinge. The axis runs up, forward, and medially, so the motion is a mix of inversion, adduction, and plantarflexion, which together are called supination of the foot.",
    bodies: ["calcn"],
    dofs: [
      hip("subtalar_angle", "Inversion", "Eversion", "Triplanar", "Oblique, through the talus",
        "Inversion turns the sole inward. Eversion turns it outward. Tibialis posterior is the strongest inverter. Fibularis longus and brevis evert and also plantarflex.",
        "Often taught as about 35° inversion and 15° eversion. The model axis allows about 20° each way.",
        [m("tibpost", "prime"), m("tibant", "synergist")],
        [m("perlong", "prime"), m("perbrev", "prime")],
      ),
    ],
  },
  {
    id: "toes",
    title: "Toes",
    region: "Lower limb",
    sided: true,
    kind: "model",
    summary: "The metatarsophalangeal joint of the model. The toes are one body, so this is a combined toe hinge rather than five separate digits.",
    bodies: ["toes"],
    dofs: [
      hip("mtp_angle", "Extension", "Flexion", "Sagittal", "Through the metatarsal heads",
        "Extension lifts the toes, which is what the trailing foot does at push-off. Flexion curls them down. The long toe extensors also dorsiflex the ankle, so they show up there too.",
        "The model allows about 30° each way. Great-toe extension in gait needs closer to 60° at the first MTP joint.",
        [m("edl", "prime"), m("ehl", "prime")],
        [m("fdl", "prime"), m("fhl", "prime")],
      ),
    ],
  },
];

export const PATTERNS = [
  {
    id: "stand",
    title: "Anatomical position",
    detail: "The model's zero pose. Palms face forward, feet point ahead.",
    pose: {},
    focus: "hip",
    dof: "hip_flexion",
  },
  {
    id: "squat",
    title: "Squat",
    detail: "Hip flexion, knee flexion, ankle dorsiflexion, and a little trunk flexion. Quadriceps, gluteus maximus, and the adductors share the rise.",
    pose: { hip_flexion: 80, knee_angle: 95, ankle_angle: 22, lumbar_extension: -25 },
    focus: "knee",
    dof: "knee_angle",
  },
  {
    id: "heel-raise",
    title: "Heel raise",
    detail: "Plantarflexion. Soleus and gastrocnemius. The knee stays straight, so gastrocnemius can contribute.",
    pose: { ankle_angle: -35 },
    focus: "ankle",
    dof: "ankle_angle",
  },
  {
    id: "side-raise",
    title: "Arm abduction",
    detail: "Glenohumeral abduction to the model's limit. Overhead would also upwardly rotate the scapula.",
    pose: { arm_add: -100, arm_rot: -20 },
    focus: "shoulder",
    dof: "arm_add",
  },
  {
    id: "reach",
    title: "Forward reach",
    detail: "Shoulder flexion with the elbow nearly straight. Anterior deltoid and pectoralis, clavicular part.",
    pose: { arm_flex: 80, elbow_flex: 15 },
    focus: "shoulder",
    dof: "arm_flex",
  },
  {
    id: "row",
    title: "Horizontal abduction",
    detail: "Arm out to the side, then moved backward in the transverse plane. Posterior deltoid, infraspinatus, and the scapular retractors.",
    pose: { arm_flex: 70, arm_add: -80, elbow_flex: 20, arm_rot: -30 },
    focus: "shoulder",
    dof: "arm_rot",
  },
];

export const REGIONS = ["Trunk", "Upper limb", "Lower limb"];

/** Teaching changes relative to the published Rajagopal 2016 gait model.
 * Slider numbers are filled in from the model file when the panel renders.
 */
export const MODEL_CHANGES = {
  lead: "Bones, joint axes, and the 80 lower-limb muscle paths are the Rajagopal 2016 full-body gait model, as distributed with OpenSim. The list below is everything this lab adds or changes on that model.",
  kept: [
    "Bone meshes and joint frames, including the Walker knee and the patella that follows knee flexion.",
    "Coordinate signs. Positive hip flexion still swings the knee forward. Positive knee flexion still swings the foot backward.",
    "One generic adult male. Left hip adduction and rotation use the model’s slope of −1, so the left side is that model’s mirror, not a second person.",
  ],
  changes: [
    {
      title: "Pelvis turns on the femoral heads",
      model: "The pelvis is the root of the skeleton. Tilt, list, rotation, and the three pelvis translations carry the whole body, thighs included.",
      lab: "Tilt, list, and rotation keep the midpoint of the two hip joints fixed, and the hip angles are rewritten so the thighs stay with the hip sliders. The trunk still rides on the pelvis. List and axial rotation still separate the two hip centers, so one foot can leave the floor. The translation coordinates are solved for that pose. They are not sliders.",
    },
    {
      title: "Standing height stays put",
      model: "The paper does not plant the feet. The default pelvis height is 0.94 m.",
      lab: "The viewer records the lowest sole point of the neutral pose and keeps that vertical offset. Flexing a hip no longer drops the body to follow the foot. A heel raise can push the toes through the floor, and a hiked hip can lift that foot.",
    },
    {
      title: "Neck hinge",
      model: "The skull and jaw are meshes of the torso. There is no neck coordinate.",
      lab: "Skull and jaw are parented to one hinge at the base of the skull. Flexion, side-bending, and rotation are teaching angles, not a stack of cervical joints and not an OpenSim coordinate.",
    },
    {
      title: "Finger and thumb hinges",
      model: "The hand is one rigid body. Carpal and finger meshes ride together.",
      lab: "Hinges sit where the mesh boxes of the metacarpals meet the phalanges, so a fist can close. They are not measured joint centers. The thumb cannot oppose, and the carpals still move as one hand.",
    },
    {
      title: "Upper-limb and trunk muscle lines",
      model: "The arms are driven by torque actuators. The model has no muscle paths for the shoulder, elbow, forearm, wrist, scapula, or neck.",
      lab: "Lines are drawn on the bones and mirrored from right to left. They are diagrams. Muscles named in the joint text but not drawn include the abdominal obliques, quadratus lumborum, pectoralis minor, scalenes, suboccipitals, splenius, lumbricals, and interossei.",
    },
    {
      title: "Lower-limb wraps",
      model: "Many of the 80 lower-limb muscles wrap on cylinders. OpenSim solves that path iteratively.",
      lab: "Each line is pushed onto the cylinder so it bows around the bone. That is a picture of the wrap, not the published solver, and some lines can still pass through bone.",
    },
    {
      title: "Scapula, clavicle, and the spine",
      model: "The scapulae and clavicles are part of the rib-cage mesh. One lumbar joint moves the whole torso. Vertebrae are not separate joints.",
      lab: "Those parts still move only with the trunk. Scapular elevation, depression, protraction, retraction, and upward and downward rotation, including scapulohumeral rhythm, are a written lesson. They do not move the mesh. The toes stay one body, so the toe slider is the model’s combined metatarsophalangeal hinge.",
    },
    {
      title: "Clinical notes and muscle roles",
      model: "The model file stores coordinate ranges, frames, and muscle paths. It does not store nerves, origins, insertions, or prime-mover labels.",
      lab: "Those sentences are written for this lab. The clinical ranges are adult guides in the AAOS and Norkin & White tradition, not measurements of this skeleton. Prime mover, synergist, and antagonist colors describe the action in anatomical position. A muscle’s job changes with posture, and the colors do not follow that.",
    },
    {
      title: "Example poses",
      model: "The published pose is the model’s zero, with the palms forward and the feet pointing ahead.",
      lab: "Squat, heel raise, arm abduction, forward reach, and horizontal abduction are poses composed for the lab. They are not poses from the paper.",
    },
  ],
};

export function muscleBase(name) {
  return name.replace(/_(r|l)$/, "");
}

export function sidedCoord(dofId, side, joint) {
  if (joint && joint.sided === false) return dofId;
  if (
    dofId.startsWith("pelvis_") ||
    dofId.startsWith("lumbar_") ||
    dofId.startsWith("cervical_")
  ) {
    return dofId;
  }
  const suffix = side === "left" || side === "l" ? "l" : "r";
  return `${dofId}_${suffix}`;
}
